# Generated by Django 2.1.5 on 2019-02-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(max_length=255, unique=True)),
                ('full_description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='media/images')),
                ('alt', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('coast', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
    ]
